name: Update API docs for EESSI testsuite
on:
  # We manually trigger this right before/after a release of the EESSI test suite
  # As this is the moment we want to update our API docs
  # Automation into a Github CI makes sure we don't have to locally build the docs and create a PR every time
  workflow_dispatch:
  push:
jobs:
  update_testsuite_apidocs:
    # if: github.repository_owner == 'EESSI'   # Prevent running on forks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.10'
          architecture: x64

      - name: checkout test suite
        uses: actions/checkout@v4
        with:
          repository: eessi/test-suite
          # Needs to be checked out into a path, otherwise it will overwrite the checkout of the docs repo
          path: test-suite

      - name: install mkdocs + plugins
        run: |
            pip install -r requirements.txt
            pip list | grep mkdocs
            mkdocs --version

      - name: build EESSI testsuite api docs
        id: build_eessi_testsuite_api_docs
        run: |
          # TODO: first copy the original testsuite_api folder
          mkdocs build
          ./scripts/update_generated_time.sh --section testsuite_api --file mkdocs.yml
          # TODO: Do a comparison to the original testsuite_api folder
          # Then, leave a breadcrumb to decide in the create pull request step if a PR needs to be created (i.e. only if something changed)

      - name: create pull request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        if: steps.build_eessi_testsuite_api_docs.outputs.json_data_changed == 'yes'  # This needs to be updated for testsuite_apidocs
        with:
          add-paths: |
            docs/testsuite_api
            mkdocs.yml
          branch: update-testsuite-api-docs
          branch-suffix: timestamp
          commit-message: Update of automatically generated API documentation for EESSI test suite
          title: Update of API documentation for EESSI test suite
          body: ''
          token: ${{ secrets.EESSIBOT_GITHUB_TOKEN }}
          push-to-fork: EESSIbot/docs
